#ifndef PROTOCOL_H
#define PROTOCOL_H

enum ProtocolCode
{
    PROTOCOL_SERVER_CONNECTION_CHECK = 0,
    PROTOCOL_SERVER_DATA_UPDATE = 4,

    PROTOCOL_CLIENT_CONNECTION_CHECK = 100,
    PROTOCOL_CLIENT_LOGIN = 102,
    PROTOCOL_CLIENT_REGISTRATION = 103,
    PROTOCOL_CLIENT_BUY = 105,
    PROTOCOL_CLIENT_SELL = 106,
    PROTOCOL_CLIENT_SHUTDOWN = 107,
    PROTOCOL_CLIENT_LOGOUT = 108,

    PROTOCOL_SUCCESS_CONNECTION = 200,
    PROTOCOL_SUCCESS_LOGIN = 202,
    PROTOCOL_SUCCESS_REGISTRATION = 203,
    PROTOCOL_SUCCESS_DATA_UPDATE = 204,
    PROTOCOL_SUCCESS_LOT = 205,
    PROTOCOL_SUCCESS_SHUTDOWN = 207,
    PROTOCOL_SUCCESS_LOGOUT = 208,

    PROTOCOL_FAILURE_CONNECTION = 300,
    PROTOCOL_FAILURE_INCORRECT_REQUEST = 301,
    PROTOCOL_FAILURE_LOGIN = 302,
    PROTOCOL_FAILURE_DATA_UPDATE = 304,
    PROTOCOL_FAILURE_LOT = 305,
    PROTOCOL_FAILURE_SHUTDOWN = 307,
    PROTOCOL_FAILURE_LOGOUT = 308
};

#endif // PROTOCOL_H